version: "2"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app:rw
      - ./data:/data:rw
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - .:/app:rw
